output_folder: gdrive://1THOw8GIdnF2tTwKfj6dyDA9iS_HHd6XV
projects:
  sdv-dev:
  - sdv-dev/SDV
  - sdv-dev/RDT
  - sdv-dev/SDMetrics
  - sdv-dev/SDGym
  - sdv-dev/Copulas
  - sdv-dev/CTGAN
  - sdv-dev/DeepEcho
  sdv:
  - sdv-dev/SDV
  rdt:
  - sdv-dev/RDT
  sdmetrics:
  - sdv-dev/SDMetrics
  sdgym:
  - sdv-dev/SDGym
  copulas:
  - sdv-dev/Copulas
  ctgan:
  - sdv-dev/CTGAN
  deepecho:
  - sdv-dev/DeepEcho
  PyTorchLightning:
  - PyTorchLightning/deep-learning-project-template
  - PyTorchLightning/lightning-bolts
  - PyTorchLightning/lightning-flash
  - PyTorchLightning/lightning-transformers
  - PyTorchLightning/lightning-tutorials
  - PyTorchLightning/metrics
  - PyTorchLightning/pytorch-lightning
  airbyte:
  - airbytehq/airbyte
  airflow:
  - apache/airflow
  dagster:
  - dagster-io/dagster
  dbt:
  - dbt-labs/dbt-core
  determined:
  - determined-ai/determined
  earthly:
  - earthly/earthly
  feast:
  - feast-dev/feast
  featuretools:
  - alteryx/featuretools
  getsynth:
  - getsynth/bigquery-storage
  - getsynth/synth
  grafana:
  - grafana/grafana
  - grafana/k6
  - grafana/loki
  - grafana/tempo
  gretel:
  - gretelai/contact-tracing-experiment
  - gretelai/gretel-blueprints
  - gretelai/gretel-python-client
  - gretelai/gretel-synthetics
  - gretelai/gretel-tools
  - gretelai/s3-object-lambda-gretel-transforms
  huggingface:
  - huggingface/accelerate
  - huggingface/autonlp
  - huggingface/awesome-huggingface
  - huggingface/datasets
  - huggingface/huggingface_hub
  - huggingface/knockknock
  - huggingface/neuralcoref
  - huggingface/node-question-answering
  - huggingface/notebooks
  - huggingface/optimum
  - huggingface/pytorch-openai-transformer-lm
  - huggingface/swift-coreml-transformers
  - huggingface/tokenizers
  - huggingface/transformers
  mariadb:
  - MariaDB/mariadb-docker
  - MariaDB/server
  mostly:
  - mostly-ai/mostly-openapi
  - mostly-ai/paper-tabular-argn
  - mostly-ai/mostlyai
  - mostly-ai/datallm
  - mostly-ai/mostlyai-docs
  - mostly-ai/mostlyai-engine
  - mostly-ai/mostlyai-qa
  - mostly-ai/public-demo-data
  - mostly-ai/mostly-tutorials
  - mostly-ai/.github
  - mostly-ai/paper-fidelity-accuracy
  - mostly-ai/gcp-marketplace
  - mostly-ai/paper-rule-adherence
  - mostly-ai/virtualdatalab
  pandas:
  - pandas-dev/pandas
  prefect:
  - PrefectHQ/prefect
  - PrefectHQ/server
  - PrefectHQ/ui
  pycaret:
  - pycaret/pycaret
  ray:
  - ray-project/kuberay
  - ray-project/lightgbm_ray
  - ray-project/ray
  - ray-project/ray_lightning
  - ray-project/tune-sklearn
  - ray-project/xgboost_ray
  scikit-learn:
  - scikit-learn/scikit-learn
  snorkel:
  - snorkel-team/snorkel
  spacy:
  - explosion/spaCy
  ydata:
  - ydataai/ydata-synthetic
  realtabformer:
  - worldbank/REaLTabFormer
  synthcity:
  - vanderschaarlab/synthcity
  smartnoise-sdk:
  - opendp/smartnoise-sdk
  be_great:
  - kathrinse/be_great
