name: Daily collection

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect Github Data
      run: |
        github-analytics collect -v -q -t ${{ secrets.GH_ACCESS_TOKEN }} -m -c daily.yaml
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}

