name: Daily Collection

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 0 * * *'

jobs:
  daily_github_collection:
    environment: daily
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
    - name: Install dependencies
      run: |
        uv pip install .
    - name: Collect GitHub Data
      run: |
        uv run gitmetrics collect -q \
          --add-metrics \
          --config-file daily.yaml \
          --token ${{ secrets.GITHUB_TOKEN }} \
          --output-folder ${{ secrets.OUTPUT_FOLDER }}
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
  alert:
    needs: [daily_github_collection]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: failure()
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        activate-environment: true
    - name: Install dependencies
      run: |
        uv pip install .[dev]
