name: Manual collection

on:
  workflow_dispatch:
  push:

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect OSS Metrics
      run: python -m oss_metrics collect -t ${{ secrets.GITHUB_TOKEN }}
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}
