name: Weekly collection

on:
  workflow_dispatch:
    inputs:
      slack_channel:
        description: Slack channel to post the error message to if the builds fail.
        required: false
        default: "sdv-alerts-debug"

  schedule:
    - cron:  '1 0 * * 0'

jobs:
  weekly_github_collection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
    - name: Collect Github Data
      run: |
        github-analytics collect -v -q -t ${{ secrets.PERSONAL_ACCESS_TOKEN }} -m -c weekly.yaml
      env:
        PYDRIVE_CREDENTIALS: ${{ secrets.PYDRIVE_CREDENTIALS }}

  alert:
    needs: [weekly_github_collection]
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install slack dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install invoke
        python -m pip install .[dev]
    - name: Slack alert if failure
      run: python -m github_analytics.slack_utils -r ${{ github.run_id }} -c ${{ github.event.inputs.slack_channel || 'sdv-alerts' }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
